test -r /sw/bin/init.sh && . /sw/bin/init.sh

# different color scheme for the console
export CLICOLOR=1
export LSCOLORS=Gxfxcxdxbxegedabagacad

# useful commands
alias p='cd -'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias l='ls -lartG'
alias ls='ls -G'
alias s='cd ..'
alias finder='open -a finder .'
alias vvi='mvim'

# SVN
alias sign='export SVN_EDITOR=vi; svn propedit svn:ignore .'
alias sup='svn up'
alias sst='svn st'
alias sadd="svn status | grep ? | sed -e 's/?      //g' | xargs -J% svn add %"
alias srm="svn status | grep ! | sed -e 's/!      //g' | xargs -J% svn remove %"
alias srev="svn status | grep M | sed -e 's/M      //g' | xargs -J% svn revert %"

# MIX
alias ss='./script/server'
alias rs='rake spec'
alias lorem='Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
alias rails_restart='touch ./tmp/restart.txt'
alias apache_restart='sudo apachectl restart'

# GIT
alias gst='git st'
alias gad='git add .'
alias gci='git ci -a'
alias gup='git pull'

# Aliased directories
alias sweetyhigh='cd /Users/reborg/Documents/projects/ap/sweetyhigh'
alias weddingbook='cd /Users/reborg/Documents/projects/ap/weddingbook'
alias proj='cd ~/Documents/projects'
alias apsupp='cd ~/Documents/projects/ap/AgileSupport'
alias ask='cd ~/Documents/projects/ap/ask/server'
alias spike='cd ~/Documents/projects/spike'
alias pomodori='cd ~/Documents/projects/my/pomodori'
alias pomohub='cd ~/Documents/projects/my/pomohub'
alias tracking='cd /Users/reborg/Documents/projects/tracking'
alias dot='cd /Users/reborg/Documents/projects/my/dot'
alias spikes='cd /Users/reborg/Documents/projects/spikes'
alias notes='cd /Users/reborg/Documents/notes'

# SSH server access
alias askbeta='ssh askbetauser@askbeta.agilepartners.com'
alias support='ssh deploy@support.agilepartners.com'

# PATH
export PATH="/Users/reborg/Downloads/apache-maven-2.2.1/bin:/Users/reborg/projects/my/dot/cmd:/Users/reborg/Documents/cmd:/opt/local/bin:/sw/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:$PATH"

#export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH

### RUBY
export RUBYOPT=rubygems
RDOCOPT="-S -f html -T hanna"
#export GEM_HOME="/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/lib/ruby/gems/1.8/gems"
#export GEM_PATH=$GEM_HOME:"/Users/reborg/.gem/ruby/1.8"

# Load the Ruby Switcher
#source ~/Documents/cmd/ruby_switcher.sh

export PROMPT_COMMAND='PS1="\[\033[0;33m\][\!]\`if [[ \$? = "0" ]]; then echo "\\[\\033[32m\\]"; else echo "\\[\\033[31m\\]"; fi\`[\u.\h: \`if [[ `pwd|wc -c|tr -d " "` > 18 ]]; then echo "\\W"; else echo "\\w"; fi\`]\$\[\033[0m\] "; echo -ne "\033]0;`hostname -s`:`pwd`\007"'
