test -r /sw/bin/init.sh && . /sw/bin/init.sh

# different color scheme for the console
#export CLICOLOR=1
#export LSCOLORS=Gxfxcxdxbxegedabagacad
#export SVN_EDITOR=vi

# longer bash history please
HISTFILESIZE=2500

# useful alias
alias p='cd -'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias l='ls -lartG'
alias ls='ls -G'
alias s='cd ..'
alias finder='open -a finder .'
alias tailf='tail -f'
alias yy='pwd | tr -d "\n" | pbcopy' # yield current dir to clipboard
alias tomcat='cd /usr/local/Cellar/tomcat/7.0.42/libexec'
alias top='top -o cpu -O +rsize -s 5 -n 20'
alias e='vi'

# LEININGEN
alias lm='lein midje :filter -slow'
alias lt='lein with-profile test test'
alias lr='lein repl'
alias lc='lein cucumber'
la(){ lein cljsbuild auto $1; }

# HASKELL
alias cb='cabal configure; cabal build'
alias ci='cabal configure; cabal install --dependencies-only'
alias cre='cabal configure; cabal repl'
alias cru='cabal configure; cabal run'
alias ct='cabal configure --enable-tests; cabal install --only-dependencies --enable-tests; cabal test'

# RAILS
alias rs='rails server'
alias rc='rails console'

# TMUX
alias tls='tmux list-sessions'
# tns(){ tmux new-session -s $1; }
alias tns='tmux -u new-session -s ${PWD##*/}'
tas(){ tmux attach-session -dt $1; }
alias tcs='tns'
tks(){ tmux kill-session -t $1; }

# SVN
alias sign='export SVN_EDITOR=vi; svn propedit svn:ignore .'
alias sup='svn up'
alias sst='svn st'
alias sst='svn diff | less -R'
sci(){ svn commit -m $1; }
alias sadd="svn status | grep ? | sed -e 's/?      //g' | xargs -J% svn add %"
alias srm="svn status | grep ! | sed -e 's/!      //g' | xargs -J% svn remove %"
alias srev="svn status | grep M | sed -e 's/M      //g' | xargs -J% svn revert %"

# maven
#mcuke(){ mvn -o -pwithargs cuke4duke:cucumber -dcukeargs="--tag $@"; }
#alias mcuke="mvn -o -pwithargs cuke4duke:cucumber -dcukeargs=\"--tag $@\""
alias mrun='mvn clean; mvn install'
alias mtest='mvn -o surefire-report:report; open target/site/surefire-report.html'
alias mcover='mvn -o cobertura:cobertura; open target/site/cobertura/index.html'
export MAVEN_OPTS="-Xmx512m -Duser.timezone=UTC"

# GIT
feature(){ git checkout -b feature-$1; }
alias gst='git status'
alias gbr='git branch'
alias gco='git checkout'
gci(){ git commit -m "$1"; }
alias glog='git log --oneline --decorate --graph'
alias gi='git-info.sh'
alias gp='git pull --rebase'
alias gdiff='git diff'

# Aliased personal projects
alias prj='cd /Users/reborg/prj'
alias my='cd /Users/reborg/prj/my'
alias uswitch='cd /Users/reborg/prj/uswitch'
alias book='cd /Users/reborg/prj/my/book'
alias tracking='cd /Users/reborg/Dropbox/tracking'
alias dot='cd /Users/reborg/prj/my/dot'
alias notes='cd /Users/reborg/Dropbox/notes'
alias documents='cd /Users/reborg/Dropbox/documents'
alias bookshelf='cd /Users/reborg/Dropbox/bookshelf'
alias talks='cd /Users/reborg/prj/talks'
alias downloads='cd ~/Downloads'
alias crash='cd ~/Library/Logs/DiagnosticReports'
alias 3rdparties='cd /Users/reborg/prj/3rdparties'
alias spikes='cd /Users/reborg/prj/spikes'
alias luca='cd /Users/reborg/Dropbox/Documents/Luca'
alias sara='cd /Users/reborg/Dropbox/Documents/sara'

alias zk=' /Users/reborg/prj/3rdparties/zookeper/bin/zkServer.sh start-foreground'

### RUBY
#export RUBYOPT=rubygems
#RDOCOPT="-S -f html -T hanna"
#export GEM_HOME="/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/lib/ruby/gems/1.8/gems"
#export GEM_PATH=$GEM_HOME:"/Users/reborg/.gem/ruby/1.8"
# Load the Ruby Switcher
#source ~/Documents/cmd/ruby_switcher.sh

### JAVA
export JAVA_HOME=$(/usr/libexec/java_home)
# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home
# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home
# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home
# export JAVA_HOME=/Library/Java/JavaVirtualMachines/1.6.0_65-b14-462.jdk/Contents/Home
# export GROOVY_HOME=~/Downloads/groovy-1.6.9
# export ROO_HOME=~/Downloads/spring-roo-1.1.5
# export GRADLE_HOME=~/Downloads/gradle-1.0-milestone-9

### PROMPT STUFF

function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\[\033[01;31m\]${DEVBOX:=localhost} \[\033[01;32m\][\w] \[\033[01;33m\]\$(parse_git_branch)\nλ:\[\e[0m\] "

# PATHS
export PATH="$JAVA_HOME/jre/bin:$HOME/.cabal/bin:/Users/reborg/prj/my/dot/cmd:/sw/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/Users/reborg/prj/my/dot/vim/bin:$GROOVY_HOME/bin:$ROO_HOME/bin:$GRADLE_HOME/bin:/Applications/Racket v5.3.6/bin:$PATH:/opt/local/bin:$HOME/Downloads/pig-0.11.1/bin:/Applications/CMake.app/Contents/bin:/Users/reborg/prj/3rdparties/FlameGraph:/Users/reborg/Downloads/stack-0.1.5.0-x86_64-osx"
# export DYLD_LIBRARY_PATH="/Users/reborg/Downloads/opencv-2.4.8/build/lib":"/opt/local/lib"
# export LD_LIBRARY_PATH=/opt/local/lib:$LD_LIBRARY_PATH
# export LIBRARY_PATH=/opt/local/lib:$LIBRARY_PATH

# Invoke private aliases
[[ -s ~/.privaterc ]] && source ~/.privaterc

# Dockerize
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/reborg/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"

alias dps='docker ps -a'
dstop(){ docker stop $1; }
dstart(){ docker start $1; }
dtail(){ docker logs -f $1; }
dexec(){ docker exec -i -t $1; }
drm(){ docker rm $1; }
alias dimages='docker images'
alias dcrm='docker-compose rm'
alias dcstop='docker-compose stop'
alias dcup='docker-compose up -d'
alias dctail='docker-compose logs'
alias dlogs='docker-compose logs'
alias l='ls -lart'
alias drmall="docker ps -a |  awk '{print \$1}' | xargs docker rm"
alias devboxstart='/Users/reborg/prj/my/docker-boxes/start.sh'
alias devbox='/Users/reborg/prj/my/docker-boxes/connect.sh'

alias hl='highlight -O rtf ${PWD##*/} --line-numbers --font-size 24 --font Monaco --style rdark -W -J 50 -j 3 --src-lang clojure | pbcopy'

# Add GHC 7.8.3 to the PATH, via http://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.8.3.app"
if [ -d "$GHC_DOT_APP" ]; then
    export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

## gpg stuff http://superuser.com/questions/739215/gpg-with-gpg-agent-never-asks-for-passphrase
export GPG_TTY=$(tty)

## Only inside the devbox
if [ "$DEVBOX" != "localhost" ]; then

  alias vi='nvim'
  export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre

  if [ -x /usr/bin/dircolors ]; then
      test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
      alias ls='ls --color=auto'
      alias l='ls --color=auto -lart'
      alias grep='grep --color=auto'
  fi

  if [ ! -L /home/reborg/.netrc ]; then
    ln -s /Users/reborg/Dropbox/Documents/home-dot-files/.netrc .netrc
  fi

  if [ ! -L /home/reborg/.ssh ]; then
    ln -s /Users/reborg/Dropbox/Documents/home-dot-files/.ssh .ssh
  fi

  if [ ! -L /home/reborg/.privaterc ]; then
    ln -s /Users/reborg/Dropbox/Documents/home-dot-files/.privaterc .privaterc
  fi

  if [ ! -L /home/reborg/.m2 ]; then
    ln -s /Users/reborg/.m2 .m2
  fi

fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
