ln -s /Users/reborg/prj/my/dot/rc/bash_profile .bash_profile
ln -s /Users/reborg/Dropbox/Documents/home-dot-files/.netrc .netrc
ln -s /Users/reborg/prj/my/dot/rc/gitconfig .gitconfig
ln -s /Users/reborg/prj/my/dot/rc/tmux.conf .tmux.conf
ln -s /Users/reborg/prj/my/dot/rc/ackrc .ackrc
ln -s /Users/reborg/prj/my/dot/rc/vimrc .vimrc
ln -s /Users/reborg/prj/my/dot/vim .vim
ln -s /Users/reborg/prj/3rdparties/.emacs.d .emacs.d
ln -s /Users/reborg/Dropbox/Documents/home-dot-files/.ssh .ssh
