#!/usr/bin/env bash

maybeparam=$1
maybefile=$2

opencheat() {
    echo
    if [ -n "$maybefile" ]; then
      echo "opening as text"
      open -e /Users/reborg/Dropbox/notes/cheatsheets/"$maybefile".md
    else
      echo "opening as markdown"
      if [ "$DEVBOX" == "devbox" ]; then
        nvim /Users/reborg/Dropbox/notes/cheatsheets/"$maybeparam".md
      else
        vi /Users/reborg/Dropbox/notes/cheatsheets/"$maybeparam".md
      fi
    fi
}

BNAME=`basename $0`
if  [ $# -lt 1 ]; then
    echo "At least one parameter should be passed in."
    exit 0
fi

# echo "0 $0"
# echo "1 $1"
# echo "2 $2"

opencheat
