#! /bin/sh
echo ... replacing "$1" with "$2" in files matching /$3/ recursive case sensitive
#FILES=`find $PWD -iname "*.$3" -type f -print`
FILES=`grep -lr "$3" *`
for f in $FILES ; do
   sed "s.$1.$2.g" $f > temp
   mv temp $f
   echo '... found ' $f
done
